function [BW,maskedRGBImage] = lab_clf(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 25-Oct-2022
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2lab(RGB);

% % Define thresholds for channel 1 based on histogram settings
% channel1Min = 0.136;
% channel1Max = 78.467;
% 
% % Define thresholds for channel 2 based on histogram settings
% channel2Min = 5.665;
% channel2Max = 22.583;
% 
% % Define thresholds for channel 3 based on histogram settings
% channel3Min = -4.617;
% channel3Max = 23.929;

% Define thresholds for channel 1 based on histogram settings
channel1Min = 3.518;
channel1Max = 70.668;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 3.994;
channel2Max = 22.497;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.390;
channel3Max = 26.552;


% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;


% Fill holes
BW = imfill(BW, 'holes');


% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
