function [BW] = postprocessmasks(img)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB,MASK) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 25-Nov-2022
%----------------------------------------------------


% Get contours using canny
img_gray=rgb2gray(img);
BWc = edge(img_gray, "canny", 0.023);

% Get contours using sobel
% [~,threshold] = edge(img_gray,'sobel');
% fudgeFactor = 0.99;
% BWs = edge(img_gray,'sobel',threshold * fudgeFactor);


% Close mask with disk
radius = 3;
decomposition = 6;
se = strel('disk', radius, decomposition);
BWc = imclose(BWc, se);
BWc = imdilate(BWc,se);


BW = BWc;
%BWs = imcomplement(BWs);
%BW = imadd(BWc, BWs);

% Fill holes
BW = imfill(BW, 'holes');

%Open mask with disk
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);


%BW = immultiply(BW, BWs);

% Fill holes
BW = imfill(BW, 'holes');

end

